### ISSUE TITLE
Evaluate all functions inside a token list

### ISSUE THREAD

**Issue by lvjr** [lvjr/functional#10]
It is a must to have a `\evalWhole` function for evaluating all functions inside a token list. And it can also be used in `functional` library of `tabularray` package as
```latex
\begin{tblr}[evaluate=\evalWhole]{lcr}
  \evalWhole{some code}
\end{tblr}
```
or
```latex
\begin{tblr}[evaluate=*]{lcr}
  some code
\end{tblr}
```

**Comment by lvjr** [comment]
For example, from the input
```latex
a \intEval{2*3} b {\fpEval{3*2.1}} c \bgroup \dimEval{1.2pt+3.4pt} \egroup d
```
`\evalWhole` will give the output
```latex
a 6 b {6.3} c \bgroup 4.6pt \egroup d
```
The are some tricky things in implementing `\expWhole`:

1. It need to keep all spaces
2. It need to distinguish `{` and `\bgroup`
3. It need to handle functions hiding in groups

@user202729 could you provide some suggestions?

**Comment by user202729** [comment]
None other than the obvious ones unfortunately...

* \tl_analysis_map_inline, to absorb a token list count the number of { minus the number of } manually. (linear time modulo \tl_build_put_right performance. I implement something similar in https://github.com/user202729/TeXlib/blob/main/execinside.sty#L44 -- no documentation for now)
* \peek_analysis_map_inline -- you already know how to use this one, and implementation can be simpler (no need to count group level manually). Main disadvantage is, I think, it has some corner cases it cannot handle -- see the implementation.
* The expandable variants all require quadratic time.

**Comment by lvjr** [comment]
Thank you very much! By the way, I also need to add `\evalNone` function which returns its argument without touching it. Therefore
```latex
\intSet \lTmpaTl {\evalNone{\intEval{2*3}}}
```
will store `\intEval{2*3}` in `\lTmpaTl`. But in my opinion, this function is rarely used in doing daily programming.

**Comment by lvjr** [comment]
I have added `\evalWhole` and `\evalNone` functions
