### ISSUE TITLE
Errors "The variable <constant> has not been declared"

### ISSUE THREAD

**Issue by muzimuzhi** [lvjr/functional#20]
`functional` creates constants with `\<type>_set_eq:NN`, which then throws errors with `\debug_on:n { check-declarations }`.

I've opened a feature request in latex3 for adding `\<type>_const_eq:NN`
- https://github.com/latex3/latex3/issues/1629 

```tex
\documentclass{article}
\ExplSyntaxOn
\debug_on:n { check-declarations , check-expressions }
\ExplSyntaxOff

\usepackage{functional}

\begin{document}
\end{document}
```

```
$ rg '^! LaTeX Error:' functional-constant-errors.log
52:! LaTeX Error: The variable \cEmptyTl has not been declared on line 1023.
71:! LaTeX Error: The variable \cSpaceTl has not been declared on line 1024.
90:! LaTeX Error: The variable \cNoValueTl has not been declared on line 1025.
109:! LaTeX Error: The variable \cAmpersandStr has not been declared on line 1249.
128:! LaTeX Error: The variable \cAttignStr has not been declared on line 1250.
147:! LaTeX Error: The variable \cBackslashStr has not been declared on line 1251.
166:! LaTeX Error: The variable \cLeftBraceStr has not been declared on line 1252.
185:! LaTeX Error: The variable \cRightBraceStr has not been declared on line
205:! LaTeX Error: The variable \cCircumflexStr has not been declared on line
225:! LaTeX Error: The variable \cColonStr has not been declared on line 1255.
244:! LaTeX Error: The variable \cDollarStr has not been declared on line 1256.
263:! LaTeX Error: The variable \cHashStr has not been declared on line 1257.
282:! LaTeX Error: The variable \cPercentStr has not been declared on line 1258.
301:! LaTeX Error: The variable \cTildeStr has not been declared on line 1259.
320:! LaTeX Error: The variable \cUnderscoreStr has not been declared on line
340:! LaTeX Error: The variable \cZeroStr has not been declared on line 1261.
377:! LaTeX Error: The variable \cZeroFp has not been declared on line 1582.
396:! LaTeX Error: The variable \cMinusZeroFp has not been declared on line 1583.
415:! LaTeX Error: The variable \cOneFp has not been declared on line 1584.
434:! LaTeX Error: The variable \cInfFp has not been declared on line 1585.
453:! LaTeX Error: The variable \cMinusInfFp has not been declared on line 1586.
472:! LaTeX Error: The variable \cEFp has not been declared on line 1587.
491:! LaTeX Error: The variable \cPiFp has not been declared on line 1588.
510:! LaTeX Error: The variable \cOneDegreeFp has not been declared on line 1589.
547:! LaTeX Error: The variable \cEmptyClist has not been declared on line 1838.
566:! LaTeX Error: The variable \cEmptySeq has not been declared on line 2062.
```

**Comment by lvjr** [comment]
Fixed!

**Comment by muzimuzhi** [comment]
(I understand below may be out of the interest of `functional`, so just posting it as a note.)

3b141e2 (fix check-declarations errors (#20), 2024-12-14) contained some (false?) workarounds for creating fp, clist, and seq constants.

- For fp constants, `\fp_const:Nn <fp const> {<another fp const>}` can be used;
- For clist, `\exp_args:NNV \clist_const:Nn <clist const> <another clist const>` or simply `\clist_const:Nn \cEmptyClist {}`;
- For seq, `\seq_const_from_clist:Nn \cEmptySeq {}` does the trick.

From l3kernel's view, when `check-declarations` is on, after
```tex
\fp_new:N \cZeroFp
\fp_set_eq:NN \cZeroFp      \c_zero_fp
```
`\cZeroFp` is recognized as a local variable. But then `\fpSet \cZeroFp {<fp expr>}` tried to set `\cZeroFp` globally, resulting in an inconsistent local/global assignment error.

```tex
\documentclass{article}
\ExplSyntaxOn
\debug_on:n { check-declarations }
\ExplSyntaxOff

\usepackage{functional}

\begin{document}
\IgnoreSpacesOn
\prgNewFunction \myFpFunc { m } {
  \fpSet \cZeroFp {1}
  \prgReturn {\fpUse \cZeroFp}
}

\prgNewFunction \myTlFunc { m } {
  \tlSet \cEmptyTl {a}
  \prgReturn {\expValue \cEmptyTl}
}

\myFpFunc {1} % errors with a wired message
% ! LaTeX Error: Inconsistent local/global assignment
% Global assignment to a local variable '\cZeroFpx'.

\myTlFunc {a} % errors with an expected message
% ! LaTeX Error: Inconsistent local/global assignment
% Global assignment to a constant variable '\cEmptyTl'.
\IgnoreSpacesOff
\end{document}
```

As `functional` already distinguishes local from global variables, maybe it can do one more thing: distinguish constants from variables.

**Comment by lvjr** [comment]
> From l3kernel's view, when `check-declarations` is on, after 
> ```
> \fp_new:N \cZeroFp
> \fp_set_eq:NN \cZeroFp      \c_zero_fp
> ```
> `\cZeroFp` is recognized as a local variable. 

I can't understand why this will happen. It sounds like a bug of `l3debug`.

But anyway it is a good idea to go around it. Fixed.

**Comment by muzimuzhi** [comment]
> > From l3kernel's view, when `check-declarations` is on, after
> > ```tex
> > \fp_new:N \cZeroFp
> > \fp_set_eq:NN \cZeroFp      \c_zero_fp
> > ```
> > 
> > `\cZeroFp` is recognized as a local variable.
> 
> I can't understand why this will happen. It sounds like a bug of `l3debug`.

Because `l3debug` classifies non-expl3-style variables based on how they are altered at the first time, not on the variable names. See [code doc of `\__debug_chk_var_scope_aux:NN`](https://github.com/latex3/latex3/blob/71419461eff29133c031751eda18fdc2f4aa1c0e/l3kernel/l3debug.dtx#L270-L285) in `l3debug.dtx` for more info.

Also only those declared and initialized by `\<type>_const...` functions are classified as constants.

As `\cZeroFp` is declared by `\fp_new:N`, it cannot be a constant. Then since it doesn't follow the expl3 naming scheme and is first set by `\fp_set_eq:NN`, it's classified as a local fp variable. It would be classified as a global fp var if first set by `\fp_gset_eq:NN`.
